name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - '15-10-2025/Oct15-jenkins/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '15-10-2025/Oct15-jenkins/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and run tests with Maven
      run: mvn -B clean test package --file 15-10-2025/Oct15-jenkins/pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
